# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c4224c0473aede3ef19cda23ddcf9095a23963c002d46b01836bfe61f439c037130d6018e653f0367933e876528502b1eb6c06c5de89462f6b1e57c538b30cdb

test:
  secret_key_base: f186873b11d838019246e887d2e744e7e8a35059a44c6bad6dad449a0007e9b83c59b8bcb144461ba93592dfc2e7d33f669e8c9f2190a860c142c58dea717121

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
